CREATE TABLE comments (
    id BIGSERIAL PRIMARY KEY,
    movie_id BIGINT REFERENCES movies(ID) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(ID) ON DELETE CASCADE,
    content varchar(1000) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);